# Python科学计算库Numpy

确保第一个事，咱们要用的库已经安装好了

In [1]:
import numpy as np

In [2]:
array = [1,2,3,4,5]
array + 1

TypeError: can only concatenate list (not "int") to list

In [3]:
array = np.array([1,2,3,4,5])
print (type(array))

<class 'numpy.ndarray'>


In [6]:
array2 = array + 1
array2

array([3, 4, 5, 6, 7])

In [7]:
array2 +array

array([ 5,  7,  9, 11, 13])

In [8]:
array2 * array

array([ 6, 12, 20, 30, 42])

In [9]:
array[0]

2

In [10]:
array[3]

5

In [11]:
array

array([2, 3, 4, 5, 6])

In [12]:
array.shape

(5,)

In [13]:
tang_list = [1,2,3,4,5]
tang_list.shape

AttributeError: 'list' object has no attribute 'shape'

In [14]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])