### array数组的数值计算

In [1]:
import numpy as np
tang_array = np.array([[1,2,3],[4,5,6]])
tang_array

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
np.sum(tang_array)

21

In [ ]:
指定要进行的操作是沿着什么轴（维度）

In [3]:
np.sum(tang_array,axis=0)

array([5, 7, 9])

In [4]:
tang_array.ndim

2

In [5]:
np.sum(tang_array,axis=1)

array([ 6, 15])

In [6]:
np.sum(tang_array,axis=-1)

array([ 6, 15])

In [7]:
tang_array.sum()

21

In [8]:
tang_array.sum(axis = 0)

array([5, 7, 9])

In [9]:
tang_array.sum(axis = 1)

array([ 6, 15])

In [11]:
tang_array.prod()

720

In [12]:
tang_array.prod(axis = 0)

array([ 4, 10, 18])

In [13]:
tang_array.prod(axis = 1)

array([  6, 120])

In [14]:
tang_array.min()

1

In [15]:
tang_array.min(axis = 0)

array([1, 2, 3])

In [16]:
tang_array.min(axis = 1)

array([1, 4])

In [17]:
tang_array.max()

6

找到索引位置

In [18]:
tang_array.argmin()

0

In [19]:
tang_array.argmin(axis = 0)

array([0, 0, 0], dtype=int64)

In [20]:
tang_array.argmin(axis=1)

array([0, 0], dtype=int64)

In [22]:
tang_array.argmax()

5

In [23]:
tang_array.mean()

3.5

In [24]:
tang_array.mean(axis = 0)

array([ 2.5,  3.5,  4.5])

标准差

In [28]:
tang_array.std()

1.707825127659933

In [29]:
tang_array.std(axis = 1)

array([ 0.81649658,  0.81649658])

方差的计算

In [27]:
tang_array.var()

2.9166666666666665

In [30]:
tang_array

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
tang_array.clip(2,4)

array([[2, 2, 3],
       [4, 4, 4]])

In [33]:
tang_array = np.array([1.2,3.56,6.41])

In [34]:
tang_array.round()

array([ 1.,  4.,  6.])

In [35]:
tang_array.round(decimals=1)

array([ 1.2,  3.6,  6.4])