### Numpy的随机模块

In [10]:
import numpy as np
#所有的值都是从0到1
np.random.rand(3,2)

array([[ 0.87876027,  0.98090867],
       [ 0.07482644,  0.08780685],
       [ 0.6974858 ,  0.35695858]])

In [11]:
#返回的是随机的整数，左闭右开
np.random.randint(10,size = (5,4))

array([[8, 0, 3, 7],
       [4, 6, 3, 4],
       [6, 9, 9, 8],
       [9, 1, 4, 0],
       [5, 9, 0, 5]])

In [15]:
np.random.rand()

0.5595234784766201

In [17]:
np.random.random_sample()

0.8279581297618884

In [25]:
np.random.randint(0,10,3)

array([7, 7, 5])

In [27]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([ 0.05754667, -0.07006152,  0.06810326, -0.11012173,  0.10064039,
       -0.06935203,  0.14194363,  0.07428931, -0.07412772,  0.12112031])

In [38]:
np.set_printoptions(precision = 2)

In [39]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([ 0.01,  0.02,  0.12, -0.01, -0.04,  0.07,  0.14, -0.08, -0.01, -0.03])

### 洗牌

In [93]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.random.shuffle(tang_array)

In [105]:
tang_array

array([6, 2, 5, 7, 4, 3, 1, 0, 8, 9])

### 随机的种子

In [91]:
np.random.seed(100)

In [92]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([-0.17,  0.03,  0.12, -0.03,  0.1 ,  0.05,  0.02, -0.11, -0.02,  0.03])