In [1]:
import numpy as np


### 使用Numpy读写数据

In [3]:
%%writefile tang.txt
1 2 3 4 5 6
2 3 5 8 7 9

Writing tang.txt


In [11]:
data = []
with open('tang.txt') as f:
    for line in f.readlines():
        fileds = line.split()
        cur_data = [float(x) for x in fileds]
        data.append(cur_data)
data = np.array(data)
data

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 2.,  3.,  5.,  8.,  7.,  9.]])

In [12]:
data = np.loadtxt('tang.txt')
data

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 2.,  3.,  5.,  8.,  7.,  9.]])

In [13]:
%%writefile tang2.txt
1,2,3,4,5,6
2,3,5,8,7,9


Writing tang2.txt


In [15]:
data = np.loadtxt('tang2.txt',delimiter = ',')
data

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 2.,  3.,  5.,  8.,  7.,  9.]])

In [16]:
%%writefile tang2.txt
x,y,z,w,a,b
1,2,3,4,5,6
2,3,5,8,7,9

Overwriting tang2.txt


In [18]:
data = np.loadtxt('tang2.txt',delimiter = ',',skiprows = 1)
data

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 2.,  3.,  5.,  8.,  7.,  9.]])

* 'tang2.txt':路径最好放到和代码一起
* skiprows : 去掉几行
* delimiter = ',' :分隔符
* usecols = (0,1,4) ：指定使用哪几列

In [19]:
tang_array = np.array([[1,2,3],[4,5,6]])

In [20]:
np.savetxt('tang4.txt',tang_array)

In [21]:
np.savetxt('tang4.txt',tang_array,fmt='%d')

In [22]:
np.savetxt('tang4.txt',tang_array,fmt='%d',delimiter = ',')

In [23]:
np.savetxt('tang4.txt',tang_array,fmt='%.2f',delimiter = ',')

### 读写array结构

In [25]:
tang_array = np.array([[1,2,3],[4,5,6]])
np.save('tang_array.npy',tang_array)

In [26]:
tang = np.load('tang_array.npy')
tang

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
tang_array2 = np.arange(10)
tang_array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.savez('tang.npz',a=tang_array,b=tang_array2)

In [29]:
data = np.load('tang.npz')

In [30]:
data.keys()

['b', 'a']

In [31]:
data['a']

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
data['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])