## Numpy练习题

打印当前Numpy版本

In [2]:
import numpy as np

In [3]:
print (np.__version__)

1.13.0


构造一个全零的矩阵，并打印其占用的内存大小

In [4]:
z = np.zeros((5,5))
print ('%d bytes'%(z.size * z.itemsize))

200 bytes


打印一个函数的帮助文档，比如numpy.add

In [5]:
print (help(np.info(np.add)))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

创建一个10-49的数组，并将其倒序排列

In [8]:
tang_array = np.arange(10,50,1)
tang_array = tang_array[::-1]
tang_array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

找到一个数组中不为0的索引

In [9]:
np.nonzero([1,2,3,4,5,0,0,0,1234,0,1])

(array([ 0,  1,  2,  3,  4,  8, 10], dtype=int64),)

随机构造一个3*3矩阵，并打印其中最大与最小值

In [12]:
tang_array = np.random.random((3,3))
tang_array.min()
tang_array.max()

0.79701003154459982

构造一个5*5的矩阵，令其值都为1，并在最外层加上一圈0

In [19]:
tang_array = np.ones((5,5))
tang_array = np.pad(tang_array,pad_width = 2,mode = 'constant',constant_values = 0)
tang_array

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [18]:
#print (help(np.pad))

构建一个shape为（6，7，8）的矩阵，并找到第100个元素的索引值

In [20]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

对一个5*5的矩阵做归一化操作

In [21]:
tang_array = np.random.random((5,5))
tang_max = tang_array.max()
tang_min = tang_array.min()
tang_array = (tang_array-tang_min)/(tang_max - tang_min)
tang_array

array([[ 0.90569013,  0.6030574 ,  0.69304289,  0.62972179,  1.        ],
       [ 0.219137  ,  0.99328655,  0.93024014,  0.19316542,  0.        ],
       [ 0.55533546,  0.92970326,  0.22950341,  0.9175972 ,  0.12021555],
       [ 0.67704953,  0.99088312,  0.06454256,  0.99668114,  0.45911364],
       [ 0.00530232,  0.2157325 ,  0.5527894 ,  0.53338114,  0.40881779]])

找到两个数组中相同的值

In [31]:
z1 = np.random.randint(0,10,10) 
z2 = np.random.randint(0,10,10)
print (z1)
print (z2)
print (np.intersect1d(z1,z2))

[7 1 0 3 9 3 4 5 4 4]
[8 2 6 1 4 1 0 7 9 5]
[0 1 4 5 7 9]


得到今天 明天 昨天的日期

In [34]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tommorow = np.datetime64('today','D') + np.timedelta64(1,'D')

In [35]:
yesterday

numpy.datetime64('2017-11-21')

In [36]:
today

numpy.datetime64('2017-11-22')

In [37]:
tommorow

numpy.datetime64('2017-11-23')

得到一个月中所有的天

In [38]:
np.arange('2017-10','2017-11',dtype='datetime64[D]')

array(['2017-10-01', '2017-10-02', '2017-10-03', '2017-10-04',
       '2017-10-05', '2017-10-06', '2017-10-07', '2017-10-08',
       '2017-10-09', '2017-10-10', '2017-10-11', '2017-10-12',
       '2017-10-13', '2017-10-14', '2017-10-15', '2017-10-16',
       '2017-10-17', '2017-10-18', '2017-10-19', '2017-10-20',
       '2017-10-21', '2017-10-22', '2017-10-23', '2017-10-24',
       '2017-10-25', '2017-10-26', '2017-10-27', '2017-10-28',
       '2017-10-29', '2017-10-30', '2017-10-31'], dtype='datetime64[D]')

得到一个数的整数部分


In [40]:
z = np.random.uniform(0,10,10)
np.floor(z)

array([ 0.,  6.,  4.,  7.,  9.,  7.,  9.,  4.,  2.,  1.])

构造一个数组，让它不能被改变

In [41]:
z = np.zeros(5)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

打印大数据的部分值，全部值

In [47]:
np.set_printoptions(threshold=5)
z = np.zeros((15,15))
z

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

找到在一个数组中，最接近一个数的索引

In [50]:
z = np.arange(100)
v = np.random.uniform(0,100)
print (v)
index = (np.abs(z-v)).argmin()
print (z[index])

37.07835396675624
37


32位float类型和32位int类型转换

In [52]:
z = np.arange(10,dtype=np.int32)
print (z.dtype)
z = z.astype(np.float32)
print (z.dtype)

int32
float32


打印数组元素位置坐标与数值

In [53]:
z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(z):
    print (index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


按照数组的某一列进行排序

In [55]:
z = np.random.randint(0,10,(3,3))
print (z)
print (z[z[:,1].argsort()])

[[3 3 9]
 [4 1 0]
 [1 0 6]]
[[1 0 6]
 [4 1 0]
 [3 3 9]]


统计数组中每个数值出现的次数

In [56]:
z = np.array([1,1,1,2,2,3,3,4,5,8])
np.bincount(z)

array([0, 3, 2, ..., 0, 0, 1], dtype=int64)

如何对一个四维数组的最后两维来求和

In [58]:
z = np.random.randint(0,10,(4,4,4,4))
res = z.sum(axis=(-2,-1))
res

array([[50, 54, 48, 85],
       [53, 51, 78, 63],
       [84, 87, 75, 83],
       [57, 83, 80, 61]])

交换矩阵中的两行

In [60]:
z = np.arange(25).reshape(5,5)
z[[0,1]] = z[[1,0]]
z


array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

找到一个数组中最常出现的数字

In [62]:
z = np.random.randint(0,10,50)
print (np.bincount(z).argmax())

6


快速查找TOP K

In [66]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5
print (z[np.argpartition(-z,n)[:n]])

[9995 9996 9997 9999 9998]


去除掉一个数组中，所有元素都相同的数据

In [87]:
np.set_printoptions(threshold=np.nan)
z = np.random.randint(0,3,(10,3))
z

array([[0, 0, 1],
       [2, 0, 0],
       [1, 0, 2],
       [2, 2, 2],
       [1, 1, 0],
       [1, 2, 2],
       [2, 0, 1],
       [2, 1, 0],
       [0, 2, 1],
       [0, 1, 2]])

In [90]:
e = np.all(z[:,1:] == z[:,:-1],axis = 1)
print (e)

[False False False  True False False False False False False]


In [73]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,5])
np.all(a == b)

False

In [71]:
np.any(a == b)

True